### ISSUE TITLE
Header editing

### ISSUE THREAD

**Issue by asphodel42** [Anastas18/FirstTeamWork_#21]
- [x] Change href for pages redirect.
![image](https://github.com/Anastas18/FirstTeamWork_/assets/102360508/8f59d18a-e63b-4cd4-93f6-ab9c61789e87)

- [x] Move header to base.html

- [x] Make better design
![image](https://github.com/Anastas18/FirstTeamWork_/assets/102360508/f3ea053b-1c14-4a69-8338-7676bd6523af)

**Comment by GoldSatan** [comment]
![image](https://github.com/Anastas18/FirstTeamWork_/assets/73445130/f54ce8d1-7b73-4ff0-a5fb-a3dbe46b44ce)
